services:
  - type: web
    name: hotel-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString

databases:
  - name: hotel-db
    databaseName: hotel_management
    plan: free